const images = [
    "https://the-books-kingdom-server.onrender.com/images/Asset1@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset2@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset3@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset4@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset5@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset6@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset7@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset8@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset9@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset10@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset11@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset12@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset13@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset14@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset15@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset16@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset17@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset18@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset19@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset20@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset21@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset22@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset23@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset24@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset25@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset26@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset27@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset28@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset29@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset30@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset31@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset32@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset33@4x.png",
    "https://the-books-kingdom-server.onrender.com/images/Asset34@4x.png"
]

export default images